language: python
python:
  - "3.5"
node_js:
  - "6.9"
# commands to install dependencies
install:
  - pip install -r requirements.txt
  - cd Explainability/client
  - npm install
# command to run tests
script:
  - cd ../..
  - ./manage.py test restapi
  - cd Explainability/client
  - npm test